version: '3.8'

services:
  app:
    build: .
    command: sh -c "uvicorn api.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      # ホストマシンのポート8000を、docker内のポート8000に接続する
      - "8000:8000"
    volumes:
      - .:/app

  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
